[package]
name = "spacy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8.1", default-plugins = false, plugins = [] }
bevy_rapier3d = { version = "0.16.2" }

[profile.dev.package."*"]
opt-level = 2

[profile.dev]
opt-level = 1
